---
title: "My Awesome Report"
author: Bjorn
format: html
---

```{r}
#| label: setup
#| include: false
library(tidyverse)
library(here)

interviews <- read_csv(here("data/SAFI_clean.csv"), na = "NULL")
```


<!--
# Title
## Section
### Subsection
#### Subsubsection
##### etc

This is regular text.
-->

## Introduction section

This ***report*** uses the **tidyverse** package along with the *SAFI* dataset,
which has columns that include:

- village
- interview_date
- no_members
- years_liv
- respondent_wall_type
- rooms

Ordered list:

1. village
2. years_liv
3. rooms

Nested items:

- village
  + Name of village
- no_members
  * How many family members lived in a house

## Results

```{r}
#| label: tbl-mean-members
#| echo: false
#| message: false
#| tbl-cap: "This is a caption."
interviews %>% 
  filter(!is.na(memb_assoc)) %>% 
  group_by(village, memb_assoc) %>% 
  summarise(mean_no_membrs = mean(no_membrs)) %>% 
  knitr::kable(
    col.names = c("Village", "Member Association", "Mean number of members")
  )
```



